columns:
  - length: int64
  - width: int64
  - height: int64
  - bkwt: int64
  - days_until_departure: int64
  - bkvol: int64
  - is_dmv: int64
  - rcsvol: float64
  - delta_vol: float64
  - product_type_arm: int64
  - product_type_avi: int64
  - product_type_dgr: int64
  - product_type_gen: int64
  - product_type_hum: int64
  - product_type_per: int64
  - product_type_val: int64
  - product_type_vun: int64
  
numerical_columns:
  - length
  - width
  - height
  - bkwt
  - days_until_departure
  - bkvol
  - is_dmv
  - rcsvol
  - delta_vol
  - product_type_arm
  - product_type_avi
  - product_type_dgr
  - product_type_gen
  - product_type_hum
  - product_type_per
  - product_type_val
  - product_type_vun